### PR TITLE
move to archive

### PR DESCRIPTION
**Pull request by elharo**
@tswast

### CODE REVIEW

**Comment by tswast** [comment]
I still a few references to this in code search for "appengine-php-wordpress-starter-project"

/cc @frankyn @ace-n who can handle this while I'm out next week.

**Comment by elharo** [comment]
I've gotten rid of the obvious references to this project in google3.

**Comment by frankyn** [comment]
@elharo could you also fix the redirect under appengine/docs: /appengine/_redirects.yaml ?

**Comment by frankyn** [comment]
Acknowledging references are no longer under the cloudsite path. Moving forward with archival.

**Pull request merged**
