### PR TITLE
removes zip blobs

### PR DESCRIPTION
**Pull request by maxhille**
I see no point in providing binary blobs:
- the step-by-step docs use git cloning to set this up
- they are extra work to keep them in sync
- git should not be used to serve big blobs

### CODE REVIEW

**Comment by tmatsuo** [comment]
Hi @maxhille First of all, thanks for the contribution!

I have a new plan for supporting WordPress on App Engine standard. I have already implemented the helper script for App Engine flexible environment at:
https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/flexible/wordpress

My plan is to add App Engine standard support to that helper script. So I would rather focus on the new setup script rather than merging all of yours.

WDYT?

Also, can you sign the Google Corporate CLA at:
https://cla.developers.google.com/
?

Thanks!

**Comment by maxhille** [comment]
I just signed the CLA.

The new starter projects looks good. I think this old one should be deleted then as not to point people in the wrong direction.

**Comment by tmatsuo** [comment]
@maxhille 

Thanks. I think those zip files are used in [the quickstart page](http://googlecloudplatform.github.io/appengine-php-wordpress-starter-project/), although I agree we should use `files` for this purpose. Let me talk with this project's maintainer.

BTW, now the new script supports App Engine standard environment too. I wrote a blog post about it:
https://wp.gaeflex.ninja/2016/04/07/running-wordpress-on-app-engine-standard-environment/

Re: deleting this repo
Agreed. I will try to deprecate this repo once the new script is proven to be useful.

**Comment by maxhille** [comment]
@tmatsuo The zips are indeed used on the quickstart page, but not on the project's README steps. Those two should be kept in sync I think. And to reduce complexity and have a simple solutions, maybe the README's steps should be put on the quickstart page (is that automatable?). That way no one would miss the zips. I think having to clone git repos is fine in today's world for devs.

**Comment by maxhille** [comment]
closing due to obsolescense

**Pull request closed without merging**
